function I_max = A2_MaximumCurrent(R_20, alpha, T_mat, T_ref, T_env, k, diameter, length)
% =========================================================================
% FUNCTION: calculateMaxCurrent
% =========================================================================
% Description:
% Calculates the maximum allowable continuous electrical current (I_max)
% for a conductor. This is determined by the point of thermal equilibrium
% where the heat generated by the current (Joule heating) equals the heat
% dissipated to the environment, with the conductor at its maximum rated
% temperature (T_mat).
%
% The calculation is based on the heat balance equation:
%   P_generated = P_dissipated
%   R_Tmat * I_max^2 = k * (T_mat - T_env) * SurfaceArea
%
% Inputs:
%   R_20     - Resistance at reference temperature (20°C) [Ohm]
%   alpha    - Temperature coefficient of resistance [1/°C]
%   T_mat    - Maximum allowable material temperature [°C]
%   T_ref    - Reference temperature for resistance (e.g., 20°C) [°C]
%   T_env    - Ambient environment temperature [°C]
%   k        - Heat dissipation factor [W / (m^2 * °C)]
%   diameter - Conductor diameter [m]
%   length   - Conductor length [m]
%
% Output:
%   I_max    - Maximum allowable current [A]
% =========================================================================

% 1. Calculate the conductor's resistance at its maximum temperature
R_Tmat = A3_ResistanceTemperatureCorrection(R_20, alpha, T_mat, T_ref);

% 2. Calculate the conductor's outer surface area
% SurfaceArea = pi * D * L
surfaceArea = pi * diameter * length; % [m^2]

% 3. Calculate total heat dissipation at the maximum temperature
% P_dissipated = k * (T_mat - T_env) * SurfaceArea
P_dissipated_max = k * (T_mat - T_env) * surfaceArea; % [Watts]

% 4. Solve for I_max from the power equation P = I^2 * R
% I_max = sqrt(P_dissipated_max / R_Tmat)
if P_dissipated_max < 0 || R_Tmat <= 0
    I_max = 0; % Avoid complex numbers or division by zero if inputs are invalid
else
    I_max = sqrt(P_dissipated_max / R_Tmat);
end

end
