function T_eq = A4_ThermalEquilibrium(I, R_20, alpha, T_ref, T_env, k, diameter, length)
% =========================================================================
% FUNCTION: solveThermalEquilibrium
% =========================================================================
% Description:
% Calculates the equilibrium temperature (T_eq) of a conductor for a given
% steady-state current (I). The equilibrium temperature is reached when the
% heat generated by the current equals the heat dissipated to the environment.
%
% The function solves the following heat balance equation for T_eq:
%   P_generated(T_eq) = P_dissipated(T_eq)
%   R_20*(1+alpha*(T_eq-T_ref))*I^2 = k*(T_eq-T_env)*SurfaceArea
%
% This is rearranged to solve directly for T_eq.
%
% Inputs:
%   I        - Current flowing through the conductor [A]
%   R_20     - Resistance at reference temperature (20°C) [Ohm]
%   alpha    - Temperature coefficient of resistance [1/°C]
%   T_ref    - Reference temperature for resistance (e.g., 20°C) [°C]
%   T_env    - Ambient environment temperature [°C]
%   k        - Heat dissipation factor [W / (m^2 * °C)]
%   diameter - Conductor diameter [m]
%   length   - Conductor length [m]
%
% Output:
%   T_eq     - The equilibrium temperature of the conductor [°C]
% =========================================================================

% Calculate conductor surface area
surfaceArea = pi * diameter * length; % [m^2]

% To solve for T_eq, we rearrange the heat balance equation:
% R_20*I^2 + R_20*I^2*alpha*T_eq - R_20*I^2*alpha*T_ref = k*surfaceArea*T_eq - k*surfaceArea*T_env
% T_eq * (k*surfaceArea - R_20*I^2*alpha) = R_20*I^2 * (1 - alpha*T_ref) + k*surfaceArea*T_env

% Define numerator and denominator for clarity
numerator = R_20 * I^2 * (1 - alpha * T_ref) + k * surfaceArea * T_env;
denominator = k * surfaceArea - R_20 * I^2 * alpha;

% Calculate equilibrium temperature
if denominator <= 0
    % This is a condition for thermal runaway, where heat is generated
    % faster than it can be dissipated. Temperature would rise indefinitely.
    T_eq = inf;
else
    T_eq = numerator / denominator;
end

end
